name: Build and upload Sphinx docs

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: test
        run: |
          pwd
          find ./

      - name: Build and Commit
        uses: sphinx-notes/pages@master
        with:
          repository_path: ./pylo

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages